############
#
# Copyright (c) 2024 Maxim Yudayev and KU Leuven eMedia Lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Created 2024-2025 for the KU Leuven AidWear, AidFOG, and RevalExo projects
# by Maxim Yudayev [https://yudayev.com].
#
# ############


host_ip : "192.168.68.101"
is_master_broker: False

remote_subscriber_ips: 
  - "192.168.68.100"
remote_publisher_ips: []

is_remote_kill: True
remote_kill_ip: "192.168.68.100" # IP of Broker that delegates the primary kill signal (i.e CLI or GUI)


logging_spec:
  stream_period_s     : 10
  
  stream_hdf5         : True
  stream_csv          : False
  stream_video        : True
  stream_audio        : False
  # incremental_saving  : True
  # incremental_period  : 90

  dump_csv            : False
  dump_hdf5           : False
  dump_video          : False
  dump_audio          : False

  video_codec_config_filepath : "resources/codecs/backpack_h264_qsv.yml" 
  video_codec_num_cpu : 1

  audio_format        : "wav" # currently only supports WAV

producer_specs:
  # Stream from the DOTs lower limb tracking.
  - class: "DotsStreamer"
    device_mapping:
      pelvis          : "40195BFD8029009B"
      knee_right      : "40195BF3809B0018"
      foot_right      : "40195BFD80290019"
      knee_left       : "40195BF3809B00D1"
      foot_left       : "40195BFD802900A0"
    mac_mapping:
      pelvis          : "D422CD009FA1"
      knee_right      : "D422CD00A13D"
      foot_right      : "D422CD00A03C"
      knee_left       : "D422CD00A215"
      foot_left       : "D422CD009FAD"
    master_device     : "pelvis" # wireless dot relaying messages, must match a key in the `device_mapping`
    num_joints        : 5
    sampling_rate_hz  : 60 # [1, 4, 10, 12, 15, 20, 30, 60]
    payload_mode      : "RateQuantitieswMag"
    filter_profile    : "General"
    is_sync_devices   : True
    timesteps_before_stale: 600
  
  # Stream from the Pupil Labs eye tracker, including gaze and video data.
  - class: "EyeStreamer"
    pupil_capture_ip        : "localhost"
    pupil_capture_port      : "50020"
    video_image_format      : "jpeg"
    gaze_estimate_stale_s   : 0.2
    is_binocular            : True # uses both eyes for gaze data and for video
    is_stream_video_world   : True
    is_stream_video_eye     : False
    is_stream_fixation      : True
    is_stream_blinks        : True
    shape_video_world: 
      - 720
      - 1280
      - 3
    shape_video_eye0: 
      - 192
      - 192
      - 3
    shape_video_eye1: 
      - 192
      - 192
      - 3
    fps_video_world       : 30.0
    fps_video_eye0        : 120.0
    fps_video_eye1        : 120.0


consumer_specs: []

pipeline_specs: []
